### PR TITLE
Sklearnization of splitter

### PR DESCRIPTION
**Pull request by parthgvora**
Thanks for contributing. If this is your first time,
make sure to read [contributing.md](https://github.com/adma2392/mne-hfo/blob/master/CONTRIBUTING.md)

PR Description
--------------

This is to PR in a sklearn style splitter. The main goal is to refactor the code in _split.pyx to be:
- In more or less the same construction as sklearn for easy merging down the line
- Returning a "Split Record" struct like sklearn's splitter does

I will try to achieve the following:
1. Put the entire splitter into cython; sample_proj_mat will be written in cython and the whole thing will just be a cython object. 2. No parts of it should be in Python
    a. I might have to keep the GIL just for random number generation, but this should be easily replaceable when merging with sklearn since we can use their utils
3. Remove my impurity functions & replace with sklearn's criterion function
4. Make my splitter return a SplitRecord struct like sklearn's splitter
5. Make my splitter inherit from sklearn's splitter if possible.
6. Document what else needs to be done to the builder & tree to make it fit sklearn's code structure

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/adam2392/mne-hfo/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by adam2392** [comment]
Would it helpful for us to just literally copy/paste the `_utils.pxd/pyx` files? I imagine they would be useful for the morf parts too.

**Comment by parthgvora** [comment]
> Would it helpful for us to just literally copy/paste the `_utils.pxd/pyx` files? I imagine they would be useful for the morf parts too.

It could be useful, but utils.pyx has dependency on sklearn's utils: 
> from ..utils._random cimport our_rand_r

Im not sure if this would cause a mess of dependencies if we just try to use their function or not. What do you think?

**Comment by adam2392** [comment]
> Im not sure if this would cause a mess of dependencies if we just try to use their function or not. What do you think?

I just looked at sklearn and it looks like the utils that you need is pretty short. I ported it over, so that way we can use their tested util funcs + get to nogil faster. 

We can probably continue down this "path" of copying code over as needed, and just noting which parts are sklearn and which parts are pure SPORF/morf?

**Comment by adam2392** [comment]
Some notes on what I was speccing out needs to change outside _oblique_splitter. files:
- Node -> ObliqueNode in _tree.pxd
- Adding stuff to realloc_ptr in _utils.pxd?

**Comment by adam2392** [comment]
Pattern for allowing arbitrary users to define their own sampling projection: http://conference.scipy.org/proceedings/SciPy2009/paper_1/full_text.pdf page 4

**Pull request merged**
